---
name: hf
n_gpu: 2
arch:
  # type: H3DNetCoordSkip
  type: H3DMultiTower
  # type: H3DCoordRGB
  # type: H2DCoord
  args: {}
  partial_load_state_dict: False
  vote_model: VoteFusionModuleV3
  vote_pcd_conv_model: fcgf
  # vote_pcd_conv_model: fcgf_official
  # vote_pcd_conv_model: D3Feat
  vote_out_dim: 64
  # vote_out_dim: 32
  fuse_anchor: 10000
  fuse_anchor_extra: 1000 # for rgb
  fix_pcd_conv_weight: True
  balance_weight: 0.7
  neighbor_radius: 0.075 # 2.5 * 0.03
  neighbor_max_sample: 48
  # score_type: D3Feat
  score_type: header
  # multi_fuse_layer: True
  multi_fuse_layer: False
  extra_feature_header: False

data_loader:
  type: X3DMatchFragmentDataLoader
  args:
    data_dir: data/3dmatch/
    batch_size: 1
    shuffle: true
    validation_split: 0.1
    num_workers: 4
  dataset_subset_ratio: 1.0
  pcd_voxel_size: 0.02
  # max_K_downsample_voxel_size: 0.03
  # max_K_div: 200
  max_K_downsample_voxel_size: 0.2
  max_K_div: 4
  # max_K_div: 100
  min_K: 0
  corner_size: 4
  mode: pair
  # only project visible points (which satisfy cluster radius) to its fragment
  divide_heatmap: False
  depth_trunc: 20.0
  frame_skip_step: 3
  covisible_mask: True

optimizer:
  type: Adam
  args:
    lr: 0.0001
    weight_decay: 1.0e-4
    amsgrad: true

loss:
  type: PlainLoss
  args: {}
  depth_pred_loss_weight: 1.0
  heatmap_loss_weight: 10.0
  heatmap_rgb_loss_weight: 10.0
  heatmap_pcd_loss_weight: 10.0
  heatmap_negative_weight: 0.05
  heatmap_consistency_loss: 0.1
  coord_projection_loss: 0.1
  chamfer_loss_weight: 0.0
  descriptor_loss_weight: 5.0

metrics: []

lr_scheduler:
  type: ExponentialLR
  args:
    # step_size: 10
    # gamma: 0.1
    gamma: 0.97

trainer:
  type: TrainerCoord
  epochs: 100
  save_dir: saved/
  save_period: 3
  verbosity: 2
  monitor: min val_loss
  # early_stop: 10
  tensorboard: true
  log_step: 100
  frame_batch_size: 4
  training_frame_size: 16
  subset_ratio: 301 # for each training epoch
  grad_clip_norm: 100
  clustering:
    method: weighted_clustering
    # method: mean_clustering
    depth_trunc: 6.0
    cluster_radius: 0.05
    nms_space: 0.15
    min_weight_thresh: 0
    max_iteration: 10
    min_pt_each_cluster: 5
  point_lifting:
    nms_dist: 2
    conf_thresh: 0.2


visualization:
  heatmap:
    nms_dist: 2
    conf_thresh: 0.2
